In [2]:
from spgbn import SPGBN
from pgbn import PGBN
import numpy as np

## Synthetic Data 

In [4]:
# construct Phi V = 6, K = 8
phi = np.array([[0.5, 0., 0., 1., 0., 0., 0., 0.],
                [0.5, 0., 0., 0., 1., 0., 0., 0.],
                [0., 0.5, 0., 0., 0., 1., 0., 0.],
                [0., 0.5, 0., 0., 0., 0., 1., 0.],
                [0., 0., 0.5, 0., 0., 0., 0., 1.],
                [0., 0., 0.5, 0., 0., 0., 0., 0.]])

# construct Theta K = 8, J = 10
np.set_printoptions(precision=2, suppress=True)
theta = np.random.gamma(shape = 10, scale = 1, size = (8, 10))
print(theta)

[[ 5.67 14.56  7.07 10.78  7.91  5.53 13.64 11.9   4.67  8.89]
 [11.89 12.94 12.8   6.04  6.76  5.44 15.54 10.28  6.97 10.3 ]
 [17.5   6.56  7.59 16.3  15.74  3.82  8.36  5.63 11.58 10.06]
 [11.22  8.12  7.25  6.84 12.81 12.15  9.73 12.32 15.78 19.46]
 [11.63  8.81  6.99 11.02 11.2  10.78 10.32 16.77  5.93 17.15]
 [ 7.69  5.77  6.8  10.29  7.93  8.62  3.96 11.83  8.86  5.44]
 [ 9.67  6.97  7.33  9.56  9.33  5.55 10.28 12.24  9.47  7.14]
 [10.42  8.48 11.71 10.22  5.59 10.57  6.45  6.39  6.52  9.87]]


In [5]:
visible_count_intensity = phi @ theta
visible_count = np.random.poisson(visible_count_intensity)

In [6]:
print(visible_count)

[[15 19 13  7 17 10 14 26 14 21]
 [16 15 15 13 14  4 17 21 13 30]
 [17 12 11 15 11 13 13 23 15  5]
 [11 13  9  8 10 15 21 14 16 19]
 [16 10 15 19 11  7 11  7 18 13]
 [ 7  3  6 11  9  3  3  3  2  6]]


### PGBN (1 layer, K = [8], iter = 600)

In [7]:
# K: list, contains the num of hidden units in each layer
pgbn = PGBN(K = [8], device = 'cpu')
pgbn.initial(visible_count)
pgbn.train(visible_count, 600)

Training Stage:  epoch   0 takes 0.00 seconds
Training Stage:  epoch   1 takes 0.00 seconds
Training Stage:  epoch   2 takes 0.00 seconds
Training Stage:  epoch   3 takes 0.00 seconds
Training Stage:  epoch   4 takes 0.00 seconds
Training Stage:  epoch   5 takes 0.00 seconds
Training Stage:  epoch   6 takes 0.00 seconds
Training Stage:  epoch   7 takes 0.00 seconds
Training Stage:  epoch   8 takes 0.00 seconds
Training Stage:  epoch   9 takes 0.00 seconds
Training Stage:  epoch  10 takes 0.00 seconds
Training Stage:  epoch  11 takes 0.00 seconds
Training Stage:  epoch  12 takes 0.00 seconds
Training Stage:  epoch  13 takes 0.00 seconds
Training Stage:  epoch  14 takes 0.00 seconds
Training Stage:  epoch  15 takes 0.00 seconds
Training Stage:  epoch  16 takes 0.00 seconds
Training Stage:  epoch  17 takes 0.00 seconds
Training Stage:  epoch  18 takes 0.00 seconds
Training Stage:  epoch  19 takes 0.00 seconds
Training Stage:  epoch  20 takes 0.00 seconds
Training Stage:  epoch  21 takes 0

In [8]:
# 设置显示精度为两位小数，并避免使用科学计数法
np.set_printoptions(precision=2, suppress=True)

# 使用 array2string 来格式化数组输出
Phi_str = np.array2string(pgbn.global_params.Phi[0], separator=', ', max_line_width=np.inf)
Theta_str = np.array2string(pgbn.local_params.Theta[0], separator=', ', max_line_width=np.inf)

print('Inference Phi:')
print(Phi_str)
print('Inference Theta:')
print(Theta_str)


Inference Phi:
[[0.  , 0.  , 0.  , 0.71, 0.  , 0.86, 0.1 , 0.35],
 [0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.3 , 0.37],
 [0.26, 0.5 , 0.  , 0.29, 1.  , 0.  , 0.  , 0.  ],
 [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.6 , 0.28],
 [0.46, 0.38, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
 [0.28, 0.12, 0.  , 0.  , 0.  , 0.14, 0.  , 0.  ]]
Inference Theta:
[[ 7.03,  0.  , 19.65, 42.13, 25.95,  0.61,  0.  ,  1.11,  1.45, 24.13],
 [29.99, 37.84,  0.  ,  0.5 ,  0.  , 20.58, 19.18, 11.71, 41.53,  1.53],
 [ 0.  ,  0.1 ,  4.94,  5.22,  0.01,  0.  ,  0.  ,  1.69,  0.  ,  5.75],
 [ 6.06,  0.  ,  0.05,  7.7 ,  0.  ,  7.73,  0.51,  1.06,  1.14,  0.43],
 [ 1.89,  0.16,  8.51,  0.  ,  0.  ,  0.01,  0.08, 23.11,  0.25,  0.69],
 [ 0.38,  1.92,  1.77,  0.89,  0.  ,  0.02,  0.  ,  0.39,  0.17,  0.  ],
 [ 0.  ,  0.84,  0.  ,  7.82,  0.63, 22.71,  7.35,  2.68,  0.  ,  3.03],
 [43.16, 44.56, 14.47, 10.21, 40.56,  0.01, 47.38, 63.25, 34.87, 62.42]]


### PGBN (3 layers, K = [8,8,8], iter = 600)

In [9]:
# K: list, contains the num of hidden units in each layer
pgbn = PGBN(K = [8,8,8], device = 'cpu')
pgbn.initial(visible_count)
pgbn.train(visible_count, 600)

Training Stage:  epoch   0 takes 0.00 seconds
Training Stage:  epoch   1 takes 0.00 seconds
Training Stage:  epoch   2 takes 0.00 seconds
Training Stage:  epoch   3 takes 0.00 seconds
Training Stage:  epoch   4 takes 0.00 seconds
Training Stage:  epoch   5 takes 0.00 seconds
Training Stage:  epoch   6 takes 0.00 seconds
Training Stage:  epoch   7 takes 0.00 seconds
Training Stage:  epoch   8 takes 0.00 seconds
Training Stage:  epoch   9 takes 0.00 seconds
Training Stage:  epoch  10 takes 0.00 seconds
Training Stage:  epoch  11 takes 0.00 seconds
Training Stage:  epoch  12 takes 0.00 seconds
Training Stage:  epoch  13 takes 0.00 seconds
Training Stage:  epoch  14 takes 0.00 seconds
Training Stage:  epoch  15 takes 0.00 seconds
Training Stage:  epoch  16 takes 0.00 seconds
Training Stage:  epoch  17 takes 0.00 seconds
Training Stage:  epoch  18 takes 0.00 seconds
Training Stage:  epoch  19 takes 0.00 seconds
Training Stage:  epoch  20 takes 0.00 seconds
Training Stage:  epoch  21 takes 0

In [10]:
# 设置显示精度为两位小数，并避免使用科学计数法
np.set_printoptions(precision=2, suppress=True)

# 使用 array2string 来格式化数组输出
Phi_str_0 = np.array2string(pgbn.global_params.Phi[0], separator=', ', max_line_width=np.inf)
Theta_str_0 = np.array2string(pgbn.local_params.Theta[0], separator=', ', max_line_width=np.inf)
Phi_str_1 = np.array2string(pgbn.global_params.Phi[1], separator=', ', max_line_width=np.inf)
Theta_str_1 = np.array2string(pgbn.local_params.Theta[1], separator=', ', max_line_width=np.inf)
Phi_str_2 = np.array2string(pgbn.global_params.Phi[2], separator=', ', max_line_width=np.inf)
Theta_str_2 = np.array2string(pgbn.local_params.Theta[2], separator=', ', max_line_width=np.inf)

print('############ 1-th layer #############')
print('Inference Phi:')
print(Phi_str_0)
print('Inference Theta:')
print(Theta_str_0)
print('############ 2-th layer #############')
print('Inference Phi:')
print(Phi_str_1)
print('Inference Theta:')
print(Theta_str_1)
print('############ 3-th layer #############')
print('Inference Phi:')
print(Phi_str_2)
print('Inference Theta:')
print(Theta_str_2)

############ 1-th layer #############
Inference Phi:
[[0.02, 0.  , 0.49, 0.  , 0.  , 0.33, 1.  , 0.04],
 [0.  , 1.  , 0.51, 1.  , 0.  , 0.  , 0.  , 0.  ],
 [0.3 , 0.  , 0.  , 0.  , 0.  , 0.67, 0.  , 0.  ],
 [0.21, 0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.96],
 [0.33, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
 [0.14, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]]
Inference Theta:
[[53.82, 31.22, 31.8 , 47.04, 44.52, 26.27, 30.84, 30.  , 36.92, 42.87],
 [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
 [27.18, 42.41, 30.45, 25.36, 28.  , 12.9 , 20.69, 40.27, 27.46, 57.92],
 [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
 [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
 [ 0.49,  0.  ,  1.42,  0.  ,  0.  ,  0.  ,  0.  ,  9.32,  0.  ,  0.  ],
 [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
 [ 2.57,  3.8 ,  0.  ,  0.  ,  0.  , 15.29, 15.03,  8.14,  7.68,  6.55]]
############ 2-th layer #############
In

### SPGBN (1 layer, K = [8], L = [8], iter = 600)

In [11]:
# K: list, contains the num of hidden units in each layer
# L: list, contains the num of latent group in each Phi of each layer
spgbn = SPGBN(K = [8], L = [8], device = 'cpu')
spgbn.initial(visible_count)
spgbn.train(visible_count, 600)

Training Stage:  epoch   0 takes 0.03 seconds
Training Stage:  epoch   1 takes 0.00 seconds
Training Stage:  epoch   2 takes 0.00 seconds
Training Stage:  epoch   3 takes 0.00 seconds
Training Stage:  epoch   4 takes 0.00 seconds
Training Stage:  epoch   5 takes 0.00 seconds
Training Stage:  epoch   6 takes 0.00 seconds
Training Stage:  epoch   7 takes 0.00 seconds
Training Stage:  epoch   8 takes 0.00 seconds
Training Stage:  epoch   9 takes 0.00 seconds
Training Stage:  epoch  10 takes 0.00 seconds
Training Stage:  epoch  11 takes 0.00 seconds
Training Stage:  epoch  12 takes 0.00 seconds
Training Stage:  epoch  13 takes 0.00 seconds
Training Stage:  epoch  14 takes 0.00 seconds
Training Stage:  epoch  15 takes 0.00 seconds
Training Stage:  epoch  16 takes 0.00 seconds
Training Stage:  epoch  17 takes 0.00 seconds
Training Stage:  epoch  18 takes 0.00 seconds
Training Stage:  epoch  19 takes 0.00 seconds
Training Stage:  epoch  20 takes 0.00 seconds
Training Stage:  epoch  21 takes 0

In [12]:
# 设置显示精度为两位小数，并避免使用科学计数法
np.set_printoptions(precision=2, suppress=True)

# 使用 array2string 来格式化数组输出
Phi_str = np.array2string(spgbn.global_params.Phi[0], separator=', ', max_line_width=np.inf)
Theta_str = np.array2string(spgbn.local_params.Theta[0], separator=', ', max_line_width=np.inf)

print('Inference Phi:')
print(Phi_str)
print('Inference Theta:')
print(Theta_str)

Inference Phi:
[[0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.23],
 [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.2 , 0.35],
 [0.47, 0.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.18],
 [0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.8 , 0.2 ],
 [0.35, 0.57, 0.  , 0.  , 1.  , 0.  , 0.  , 0.04],
 [0.18, 0.43, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]]
Inference Theta:
[[33.55,  3.16,  0.  ,  0.07,  1.98, 21.33,  5.74, 19.06,  3.89,  1.28],
 [ 0.16, 14.51, 14.88, 30.03, 11.83,  0.04,  0.  ,  0.  ,  3.19, 17.26],
 [ 2.53,  6.27,  2.58,  0.  ,  0.01,  9.52,  8.25,  0.  ,  6.08,  0.91],
 [ 0.22,  4.93,  3.79,  0.  ,  8.39,  8.12,  2.  ,  0.01,  3.03,  1.8 ],
 [ 0.78,  0.  ,  5.12,  0.02,  1.66,  0.  ,  7.4 ,  0.  , 15.19,  0.8 ],
 [ 2.4 ,  0.  ,  8.73,  1.44,  1.16,  4.33,  0.  ,  0.  ,  0.14,  0.62],
 [ 3.5 ,  0.71,  0.  ,  0.07,  0.  ,  0.92,  0.  ,  0.  ,  0.34,  0.19],
 [52.6 , 38.91, 36.85, 33.92, 45.44,  8.36, 51.9 , 65.37, 54.79, 70.64]]


### SPGBN (1 layer, K = [8,8,8], L = [8,8,8], iter = 600)

In [13]:
# K: list, contains the num of hidden units in each layer
# L: list, contains the num of latent group in each Phi of each layer
spgbn = SPGBN(K = [8,8,8], L = [8,8,8], device = 'cpu')
spgbn.initial(visible_count)
spgbn.train(visible_count, 600)

Training Stage:  epoch   0 takes 0.00 seconds
Training Stage:  epoch   1 takes 0.00 seconds
Training Stage:  epoch   2 takes 0.00 seconds
Training Stage:  epoch   3 takes 0.00 seconds
Training Stage:  epoch   4 takes 0.00 seconds
Training Stage:  epoch   5 takes 0.00 seconds
Training Stage:  epoch   6 takes 0.00 seconds
Training Stage:  epoch   7 takes 0.00 seconds
Training Stage:  epoch   8 takes 0.00 seconds
Training Stage:  epoch   9 takes 0.00 seconds
Training Stage:  epoch  10 takes 0.00 seconds
Training Stage:  epoch  11 takes 0.00 seconds
Training Stage:  epoch  12 takes 0.00 seconds
Training Stage:  epoch  13 takes 0.00 seconds
Training Stage:  epoch  14 takes 0.00 seconds
Training Stage:  epoch  15 takes 0.00 seconds
Training Stage:  epoch  16 takes 0.00 seconds
Training Stage:  epoch  17 takes 0.00 seconds
Training Stage:  epoch  18 takes 0.00 seconds
Training Stage:  epoch  19 takes 0.00 seconds
Training Stage:  epoch  20 takes 0.00 seconds
Training Stage:  epoch  21 takes 0

In [21]:
# 设置显示精度为两位小数，并避免使用科学计数法
np.set_printoptions(precision=2, suppress=True)

# 使用 array2string 来格式化数组输出
Phi_str_0 = np.array2string(spgbn.global_params.Phi[0], separator=', ', max_line_width=np.inf)
Theta_str_0 = np.array2string(spgbn.local_params.Theta[0], separator=', ', max_line_width=np.inf)
Phi_str_1 = np.array2string(spgbn.global_params.Phi[1], separator=', ', max_line_width=np.inf)
Theta_str_1 = np.array2string(spgbn.local_params.Theta[1], separator=', ', max_line_width=np.inf)
Phi_str_2 = np.array2string(spgbn.global_params.Phi[2], separator=', ', max_line_width=np.inf)
Theta_str_2 = np.array2string(spgbn.local_params.Theta[2], separator=', ', max_line_width=np.inf)

print('############ 1-th layer #############')
print('Inference Phi:')
print(Phi_str_0)
print('Inference Theta:')
print(Theta_str_0)
print('############ 2-th layer #############')
print('Inference Phi:')
print(Phi_str_1)
print('Inference Theta:')
print(Theta_str_1)
print('############ 3-th layer #############')
print('Inference Phi:')
print(Phi_str_2)
print('Inference Theta:')
print(Theta_str_2)

############ 1-th layer #############
Inference Phi:
[[0.17, 0.17, 0.17, 0.  , 0.  , 0.29, 0.17, 0.4 ],
 [0.17, 0.17, 0.17, 0.  , 0.  , 0.39, 0.17, 0.39],
 [0.17, 0.17, 0.17, 1.  , 0.31, 0.  , 0.17, 0.  ],
 [0.17, 0.17, 0.17, 0.  , 0.31, 0.32, 0.17, 0.  ],
 [0.17, 0.17, 0.17, 0.  , 0.38, 0.  , 0.17, 0.  ],
 [0.17, 0.17, 0.17, 0.  , 0.  , 0.  , 0.17, 0.2 ]]
Inference Theta:
[[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
 [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
 [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
 [ 0.  ,  6.18,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , 28.05,  0.  ,  0.  ],
 [51.85, 30.16, 29.95, 31.63, 37.94, 37.78, 34.1 ,  4.3 , 45.53, 32.26],
 [ 0.  , 25.53,  0.  ,  0.06,  0.  ,  2.87, 30.86, 62.83,  0.  , 33.5 ],
 [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
 [33.98, 16.21, 34.08, 27.9 , 34.7 , 18.59, 16.99, 21.33, 16.73, 25.77]]
############ 2-th layer #############
In