In [50]:
from spgbn import SPGBN
from pgbn import PGBN
import numpy as np

## Synthetic Data 

In [51]:
# construct Phi V = 6, K = 8
phi = np.array([[0.5, 0., 0., 1., 0., 0., 0., 0.],
                [0.5, 0., 0., 0., 1., 0., 0., 0.],
                [0., 0.5, 0., 0., 0., 1., 0., 0.],
                [0., 0.5, 0., 0., 0., 0., 1., 0.],
                [0., 0., 0.5, 0., 0., 0., 0., 1.],
                [0., 0., 0.5, 0., 0., 0., 0., 0.]])

# construct Theta K = 8, J = 10
theta = np.random.gamma(shape = 10, scale = 1, size = (8, 10))
print(theta)

[[ 6.29  9.61  5.84  3.39  7.89 10.28  6.29  6.39 12.07  9.55]
 [11.02 14.53  9.08 17.37 12.19 10.94  8.73 11.6  10.5  10.19]
 [ 9.34 11.98 14.67  8.29 13.92 11.26  6.78  6.45 13.87 14.72]
 [ 8.68 17.42 10.9   9.01  7.97 15.35  9.32  6.18  8.56  9.67]
 [14.6  11.6   8.65  7.77  7.96  8.63  6.75 10.84 10.47  8.69]
 [ 8.61  7.57 16.93  4.93  9.04  7.67  5.22  6.21 12.57  9.66]
 [ 8.62 10.81 10.24 11.12 18.    6.77 14.58 14.87  9.53 10.06]
 [10.76 15.44 10.34  8.45  8.7  15.11  5.06 14.82 16.7  10.28]]


In [52]:
visible_count_intensity = phi @ theta
visible_count = np.random.poisson(visible_count_intensity)

In [53]:
print(visible_count)

[[ 8 18 24 12 10 19 11  4 19 27]
 [23 10 13  6 16 12 10 18 11 13]
 [14 21 19  9 11 14 10 15 22 19]
 [25 32 19 13 26 14 13 22 14 10]
 [18 16 14 12 16 19  7 13 34 18]
 [ 7  3  6  4  3  5  2  2  7  9]]


### PGBN (1 layer, K = [8], iter = 600)

In [54]:
# K: list, contains the num of hidden units in each layer
pgbn = PGBN(K = [8], device = 'cpu')
pgbn.initial(visible_count)
pgbn.train(visible_count, 600)

Training Stage:  epoch   0 takes 0.00 seconds
Training Stage:  epoch   1 takes 0.00 seconds
Training Stage:  epoch   2 takes 0.00 seconds
Training Stage:  epoch   3 takes 0.00 seconds
Training Stage:  epoch   4 takes 0.00 seconds
Training Stage:  epoch   5 takes 0.00 seconds
Training Stage:  epoch   6 takes 0.00 seconds
Training Stage:  epoch   7 takes 0.00 seconds
Training Stage:  epoch   8 takes 0.00 seconds
Training Stage:  epoch   9 takes 0.00 seconds
Training Stage:  epoch  10 takes 0.00 seconds
Training Stage:  epoch  11 takes 0.00 seconds
Training Stage:  epoch  12 takes 0.00 seconds
Training Stage:  epoch  13 takes 0.00 seconds
Training Stage:  epoch  14 takes 0.00 seconds
Training Stage:  epoch  15 takes 0.00 seconds
Training Stage:  epoch  16 takes 0.00 seconds
Training Stage:  epoch  17 takes 0.00 seconds
Training Stage:  epoch  18 takes 0.00 seconds
Training Stage:  epoch  19 takes 0.00 seconds
Training Stage:  epoch  20 takes 0.00 seconds
Training Stage:  epoch  21 takes 0

In [55]:
# 设置显示精度为两位小数，并避免使用科学计数法
np.set_printoptions(precision=2, suppress=True)

# 使用 array2string 来格式化数组输出
Phi_str = np.array2string(pgbn.global_params.Phi[0], separator=', ', max_line_width=np.inf)
Theta_str = np.array2string(pgbn.local_params.Theta[0], separator=', ', max_line_width=np.inf)

print('Inference Phi:')
print(Phi_str)
print('Inference Theta:')
print(Theta_str)


Inference Phi:
[[0.  , 0.  , 0.  , 1.  , 0.49, 0.  , 0.15, 1.  ],
 [0.  , 1.  , 0.  , 0.  , 0.  , 0.17, 0.16, 0.  ],
 [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.2 , 0.  ],
 [0.  , 0.  , 0.  , 0.  , 0.  , 0.83, 0.24, 0.  ],
 [1.  , 0.  , 1.  , 0.  , 0.46, 0.  , 0.16, 0.  ],
 [0.  , 0.  , 0.  , 0.  , 0.05, 0.  , 0.09, 0.  ]]
Inference Theta:
[[10.52,  0.64,  0.4 ,  0.  ,  7.02,  0.  ,  0.  ,  0.63,  4.31,  0.02],
 [ 1.34,  0.  ,  0.  ,  0.  ,  0.  ,  5.08,  0.66,  2.36,  0.02,  0.  ],
 [ 0.04,  0.02,  0.02,  0.  ,  0.03, 10.99,  0.  ,  8.06, 18.96,  2.25],
 [ 0.01,  0.01,  6.56,  0.  ,  5.17,  0.01,  0.  ,  0.  ,  0.  , 11.67],
 [ 0.01,  0.  ,  6.42,  5.2 ,  0.99,  0.  ,  1.04,  0.01,  0.01,  0.22],
 [13.57,  0.  ,  0.  ,  0.  , 24.22,  0.02,  0.  , 14.65,  0.  ,  0.17],
 [78.96, 94.12, 86.02, 62.71, 37.31, 49.95, 47.74, 61.99, 95.  , 71.73],
 [ 1.1 ,  0.01,  0.  ,  0.  ,  0.1 , 14.97,  0.  ,  0.  ,  1.46,  0.  ]]


### PGBN (3 layers, K = [8,8,8], iter = 600)

In [37]:
# K: list, contains the num of hidden units in each layer
pgbn = PGBN(K = [8,8,8], device = 'cpu')
pgbn.initial(visible_count)
pgbn.train(visible_count, 600)

Training Stage:  epoch   0 takes 0.00 seconds
Training Stage:  epoch   1 takes 0.00 seconds
Training Stage:  epoch   2 takes 0.00 seconds
Training Stage:  epoch   3 takes 0.00 seconds
Training Stage:  epoch   4 takes 0.00 seconds
Training Stage:  epoch   5 takes 0.00 seconds
Training Stage:  epoch   6 takes 0.00 seconds
Training Stage:  epoch   7 takes 0.00 seconds
Training Stage:  epoch   8 takes 0.00 seconds
Training Stage:  epoch   9 takes 0.00 seconds
Training Stage:  epoch  10 takes 0.00 seconds
Training Stage:  epoch  11 takes 0.00 seconds
Training Stage:  epoch  12 takes 0.00 seconds
Training Stage:  epoch  13 takes 0.00 seconds
Training Stage:  epoch  14 takes 0.00 seconds
Training Stage:  epoch  15 takes 0.00 seconds
Training Stage:  epoch  16 takes 0.00 seconds
Training Stage:  epoch  17 takes 0.00 seconds
Training Stage:  epoch  18 takes 0.00 seconds
Training Stage:  epoch  19 takes 0.00 seconds
Training Stage:  epoch  20 takes 0.00 seconds
Training Stage:  epoch  21 takes 0

In [38]:
# 设置显示精度为两位小数，并避免使用科学计数法
np.set_printoptions(precision=2, suppress=True)

# 使用 array2string 来格式化数组输出
Phi_str_0 = np.array2string(pgbn.global_params.Phi[0], separator=', ', max_line_width=np.inf)
Theta_str_0 = np.array2string(pgbn.local_params.Theta[0], separator=', ', max_line_width=np.inf)
Phi_str_1 = np.array2string(pgbn.global_params.Phi[1], separator=', ', max_line_width=np.inf)
Theta_str_1 = np.array2string(pgbn.local_params.Theta[1], separator=', ', max_line_width=np.inf)
Phi_str_2 = np.array2string(pgbn.global_params.Phi[2], separator=', ', max_line_width=np.inf)
Theta_str_2 = np.array2string(pgbn.local_params.Theta[2], separator=', ', max_line_width=np.inf)

print('############ First layer #############')
print('Inference Phi:')
print(Phi_str_0)
print('Inference Theta:')
print(Theta_str_0)
print('############ Second layer #############')
print('Inference Phi:')
print(Phi_str_1)
print('Inference Theta:')
print(Theta_str_1)
print('############ Second layer #############')
print('Inference Phi:')
print(Phi_str_2)
print('Inference Theta:')
print(Theta_str_2)

############ First layer #############
Inference Phi:
[[0.  , 0.24, 0.  , 0.  , 0.  , 1.  , 0.  , 0.  ],
 [0.  , 0.33, 0.  , 0.  , 0.  , 0.  , 0.88, 0.  ],
 [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.12, 1.  ],
 [0.  , 0.  , 1.  , 1.  , 1.  , 0.  , 0.  , 0.  ],
 [0.  , 0.34, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
 [1.  , 0.09, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]]
Inference Theta:
[[ 0.  ,  0.  ,  0.  ,  0.28,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
 [50.88, 53.56, 65.38, 52.87, 59.34, 43.89, 42.47, 49.89, 37.78, 54.4 ],
 [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
 [14.13, 23.34, 20.97, 14.37,  6.93, 15.44,  7.22,  6.2 , 14.3 ,  9.19],
 [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
 [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
 [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
 [17.17,  4.35,  8.25,  6.36,  8.71, 18.62,  7.69, 21.47, 30.92,  8.47]]
############ Second layer #############

### SPGBN (1 layer, K = [8], L = [8], iter = 600)

In [45]:
# K: list, contains the num of hidden units in each layer
# L: list, contains the num of latent group in each Phi of each layer
spgbn = SPGBN(K = [8], L = [8], device = 'cpu')
spgbn.initial(visible_count)
spgbn.train(visible_count, 600)

Training Stage:  epoch   0 takes 0.00 seconds
Training Stage:  epoch   1 takes 0.00 seconds
Training Stage:  epoch   2 takes 0.00 seconds
Training Stage:  epoch   3 takes 0.00 seconds
Training Stage:  epoch   4 takes 0.00 seconds
Training Stage:  epoch   5 takes 0.00 seconds
Training Stage:  epoch   6 takes 0.00 seconds
Training Stage:  epoch   7 takes 0.00 seconds
Training Stage:  epoch   8 takes 0.00 seconds
Training Stage:  epoch   9 takes 0.00 seconds
Training Stage:  epoch  10 takes 0.00 seconds
Training Stage:  epoch  11 takes 0.00 seconds
Training Stage:  epoch  12 takes 0.00 seconds
Training Stage:  epoch  13 takes 0.00 seconds
Training Stage:  epoch  14 takes 0.00 seconds
Training Stage:  epoch  15 takes 0.00 seconds
Training Stage:  epoch  16 takes 0.00 seconds
Training Stage:  epoch  17 takes 0.00 seconds
Training Stage:  epoch  18 takes 0.00 seconds
Training Stage:  epoch  19 takes 0.00 seconds
Training Stage:  epoch  20 takes 0.00 seconds
Training Stage:  epoch  21 takes 0

In [46]:
# 设置显示精度为两位小数，并避免使用科学计数法
np.set_printoptions(precision=2, suppress=True)

# 使用 array2string 来格式化数组输出
Phi_str = np.array2string(spgbn.global_params.Phi[0], separator=', ', max_line_width=np.inf)
Theta_str = np.array2string(spgbn.local_params.Theta[0], separator=', ', max_line_width=np.inf)

print('Inference Phi:')
print(Phi_str)
print('Inference Theta:')
print(Theta_str)

Inference Phi:
[[0.  , 0.  , 0.37, 0.  , 0.35, 0.17, 0.  , 0.  ],
 [0.  , 0.  , 0.49, 0.  , 0.39, 0.17, 0.  , 0.  ],
 [0.  , 0.  , 0.  , 1.  , 0.  , 0.17, 0.46, 1.  ],
 [0.64, 0.  , 0.  , 0.  , 0.  , 0.17, 0.07, 0.  ],
 [0.36, 1.  , 0.02, 0.  , 0.  , 0.17, 0.47, 0.  ],
 [0.  , 0.  , 0.12, 0.  , 0.26, 0.17, 0.  , 0.  ]]
Inference Theta:
[[22.52, 30.75, 23.91, 20.75,  4.17, 13.31,  9.8 ,  7.28, 30.66, 41.52],
 [ 0.  ,  0.  ,  2.68,  3.97,  6.82,  1.35,  0.84,  8.23,  0.  ,  0.19],
 [ 4.36, 34.83, 28.88, 32.62, 17.87,  0.47,  0.  ,  4.97,  1.48, 32.94],
 [ 0.02,  0.76,  0.  ,  0.  ,  0.  ,  0.14,  4.28,  0.  ,  0.  ,  1.75],
 [28.99,  0.  ,  4.88, 11.33, 39.96, 24.43, 35.42, 30.77, 17.22,  0.  ],
 [ 0.1 ,  0.1 ,  0.  ,  0.  ,  0.  ,  0.09,  0.  ,  2.96,  0.  ,  0.01],
 [ 0.06,  0.  , 22.63,  0.02, 35.72, 21.7 , 19.52,  9.48,  2.32, 16.96],
 [16.27,  4.05,  3.62,  5.09,  0.13, 22.84,  0.  , 15.51, 21.97,  0.  ]]


### SPGBN (1 layer, K = [8,8,8], L = [8,8,8], iter = 600)

In [48]:
# K: list, contains the num of hidden units in each layer
# L: list, contains the num of latent group in each Phi of each layer
spgbn = SPGBN(K = [8,8,8], L = [8,8,8], device = 'cpu')
spgbn.initial(visible_count)
spgbn.train(visible_count, 600)

Training Stage:  epoch   0 takes 0.00 seconds
Training Stage:  epoch   1 takes 0.00 seconds
Training Stage:  epoch   2 takes 0.00 seconds
Training Stage:  epoch   3 takes 0.00 seconds
Training Stage:  epoch   4 takes 0.00 seconds
Training Stage:  epoch   5 takes 0.00 seconds
Training Stage:  epoch   6 takes 0.00 seconds
Training Stage:  epoch   7 takes 0.00 seconds
Training Stage:  epoch   8 takes 0.00 seconds
Training Stage:  epoch   9 takes 0.00 seconds
Training Stage:  epoch  10 takes 0.00 seconds
Training Stage:  epoch  11 takes 0.00 seconds
Training Stage:  epoch  12 takes 0.00 seconds
Training Stage:  epoch  13 takes 0.00 seconds
Training Stage:  epoch  14 takes 0.00 seconds
Training Stage:  epoch  15 takes 0.00 seconds
Training Stage:  epoch  16 takes 0.00 seconds
Training Stage:  epoch  17 takes 0.00 seconds
Training Stage:  epoch  18 takes 0.00 seconds
Training Stage:  epoch  19 takes 0.00 seconds
Training Stage:  epoch  20 takes 0.00 seconds
Training Stage:  epoch  21 takes 0

In [49]:
# 设置显示精度为两位小数，并避免使用科学计数法
np.set_printoptions(precision=2, suppress=True)

# 使用 array2string 来格式化数组输出
Phi_str_0 = np.array2string(spgbn.global_params.Phi[0], separator=', ', max_line_width=np.inf)
Theta_str_0 = np.array2string(spgbn.local_params.Theta[0], separator=', ', max_line_width=np.inf)
Phi_str_1 = np.array2string(spgbn.global_params.Phi[1], separator=', ', max_line_width=np.inf)
Theta_str_1 = np.array2string(spgbn.local_params.Theta[1], separator=', ', max_line_width=np.inf)
Phi_str_2 = np.array2string(spgbn.global_params.Phi[2], separator=', ', max_line_width=np.inf)
Theta_str_2 = np.array2string(spgbn.local_params.Theta[2], separator=', ', max_line_width=np.inf)

print('############ First layer #############')
print('Inference Phi:')
print(Phi_str_0)
print('Inference Theta:')
print(Theta_str_0)
print('############ Second layer #############')
print('Inference Phi:')
print(Phi_str_1)
print('Inference Theta:')
print(Theta_str_1)
print('############ Second layer #############')
print('Inference Phi:')
print(Phi_str_2)
print('Inference Theta:')
print(Theta_str_2)

############ First layer #############
Inference Phi:
[[0.  , 0.17, 0.17, 0.32, 0.17, 0.  , 0.  , 0.24],
 [0.  , 0.17, 0.17, 0.  , 0.17, 0.  , 0.44, 0.22],
 [0.  , 0.17, 0.17, 0.  , 0.17, 1.  , 0.  , 0.3 ],
 [0.  , 0.17, 0.17, 0.68, 0.17, 0.  , 0.  , 0.09],
 [1.  , 0.17, 0.17, 0.  , 0.17, 0.  , 0.56, 0.  ],
 [0.  , 0.17, 0.17, 0.  , 0.17, 0.  , 0.  , 0.14]]
Inference Theta:
[[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  , 13.67,  0.  ,  0.  , 17.97,  0.82],
 [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
 [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
 [14.22, 30.38, 23.94, 19.77,  0.02,  9.16,  0.  ,  0.  , 27.38, 11.5 ],
 [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
 [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , 19.44,  0.  ],
 [15.73, 28.53, 34.45, 22.2 , 34.5 ,  7.59, 20.24, 28.6 , 14.38, 26.73],
 [61.19, 29.6 , 33.71, 42.51, 39.17, 48.28, 50.39, 46.58, 17.23, 35.18]]
############ Second layer #############